x = input("Enter a number: ")
y = input("Enter a second number: ")
remainder = int(x)%int(y)
quotient = int(x)//int(y)
print("The quotient of ", x," and ", y," is ", quotient," with a remainder of ", remainder,)
